#ifndef __UTILLOG__INNERDEF__
#define __UTILLOG__INNERDEF__

/**< 共享内存(日志存放区) */
#define UTIL_SM_LOG "Global\\{280F82FF-D72E-4146-B413-EADBE03A2E54}"
#define UTIL_SM_FLAG_SHARESEG "_SHARESEG"
#define UTIL_SM_FLAG_EVENT "_EVENT"
#define UTIL_SM_FLAG_MUTEX "_MUTEX"

/**< 共享内存(控制命令) */
#define UTIL_SM_CONTROL "Global\\{97320751-52F4-4B7F-867B-240F48DC3CC4}"
#define UTIL_SM_CTRL_FLAG_SHARESEG "_SHARESEG"
#define UTIL_SM_CTRL_FLAG_EVENT "_EVENT"
#define UTIL_SM_CTRL_FLAG_MUTEX "_MUTEX"

#endif